database:
  username: root
  password: 123456
  dbName: giligili
  dbHost: localhost
  dbPort: 3306


HttpPort: :8081


AppMode: debug


SessionSecret: setOnProduction


redis:
  addr: localhost:6379
  pwd: 123456
  db: 0
